#
# script to calculate and validate buy signal 
#  uses csvs generated by getquotes.py
#

library(plyr)  # rbind.fill
library(dplyr) # %>%
library(zoo) # rollaply
library(ggplot2)

# what window lenght do we want to use for rolling stats
windowwidth<-20

# put all the csv files into a list
quotes <- lapply(Sys.glob('data/*csv'),read.table,header=T,sep=",")

# collapse list into 1 dataframe, calculations
quotesdf <- rbind.fill(quotes) %>%
     # bad day for the stock?
     mutate(closeunder=Close<Open) %>%
     # work only within one stock (ordered by date)
     group_by(Name) %>% arrange(Date) %>% 
     # calculate rolling stats
     mutate( win.mu = c(rep(0,windowwidth-1), rollapply(Close,width=windowwidth,FUN=mean) ) ) %>%
     mutate( win.sd = c(rep(0,windowwidth-1), rollapply(Close,width=windowwidth,FUN=sd) ) ) %>%
     mutate( low.1sd = win.mu-win.sd) %>%
     # buy signal
     mutate( buy    = lag(Close) < lag(low.1sd) & Open < lag(low.1sd) ) %>%
     # don't buy if already bought!
     mutate( buy    = ifelse(lag(buy) & buy,NA,buy) )


# TODO:
#  sell
#  validate
