#
# script to calculate and validate buy signal 
#  uses csvs generated by getquotes.py
#

library(plyr)  # rbind.fill
library(dplyr) # %>%
library(ggplot2)
library(smquote) # make.history





# put all the csv files into a list
quotes <- lapply(Sys.glob('data/*csv'),read.table,header=T,sep=",")
# collapse list into 1 dataframe, calculations
quotesdf <- rbind.fill(quotes) 
# remove stocks that have too few time points

quotesdfms <- make.history(quotesdf,20)
qbak <- quotesdfms 


#see
print(unique(quotesdfm$gprct))
#data.frame(tail(quotesdf,n=100))


